## Uso de libreria Numpy
* verificacion de version y estado
* uso de la libreria np array crea los vectores  y np shape devuelve las dimensiones y los elemtos por dimension

In [11]:
import numpy as np

a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])

rows, cols = np.shape(a)

print ('Rows:{0:03d} ; Cols:{0:03d}'.format(cols, rows))
print(a)



Rows:004 ; Cols:004
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


     Poblamos un vector con numpy indicadn dimensieones y elementos

In [16]:
np.zeros((3,4)) #or empty


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Creación de vector dinamica

In [20]:

c = np.array([[10*j+i for i in range(3)] for j in range(4)])
print (c)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [25]:
x,y = np.mgrid[0:5,0:5]
print(x)
print("--------")
print(y)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
--------
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
