## Uso de libreria Numpy
* verificacion de version y estado
* uso de la libreria np array crea los vectores  y np shape devuelve las dimensiones y los elemtos por dimension

In [11]:
import numpy as np

a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])

rows, cols = np.shape(a)

print ('Rows:{0:03d} ; Cols:{0:03d}'.format(cols, rows))
print(a)



Rows:004 ; Cols:004
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


     Poblamos un vector con numpy indicadn dimensieones y elementos

In [16]:
np.zeros((3,4)) #or empty


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Creación de vector dinamica

In [20]:

c = np.array([[10*j+i for i in range(3)] for j in range(4)])
print (c)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


mgrid(rango+:rango-:dimension solo x(numero)j(opcional)) , no funciona con mutiasignacion , hay que indicarlo en el misma funcion 
si hay vectores juntos el segundo toma las dimensiones del primero 

In [48]:
x  = np.mgrid[-1:1,0:5]
print(x)
print("--------")
print(y)

[[[-1 -1 -1 -1 -1]
  [ 0  0  0  0  0]]

 [[ 0  1  2  3  4]
  [ 0  1  2  3  4]]]
--------
[[-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]]


poblamos un vector y lo cambiamos a 0 , luegro transformamos 
los valores validos a un vector comprimido

In [53]:
from scipy import sparse
X = np.random.random((5, 6)) 

X[X < 0.85] = 0

print (X)
X_csr = sparse.csr_matrix(X)

print (X_csr)

[[0.98879717 0.         0.         0.         0.         0.        ]
 [0.         0.88633501 0.         0.86246889 0.         0.85741465]
 [0.98020568 0.95081596 0.96338155 0.         0.         0.        ]
 [0.         0.         0.         0.98011596 0.         0.92616544]
 [0.         0.         0.         0.         0.         0.        ]]
  (0, 0)	0.9887971743556577
  (1, 1)	0.8863350079123218
  (1, 3)	0.8624688916644425
  (1, 5)	0.8574146548550866
  (2, 0)	0.9802056781817715
  (2, 1)	0.9508159565774831
  (2, 2)	0.9633815514305044
  (3, 3)	0.9801159552201893
  (3, 5)	0.92616544383539


indicar un seeder en el random permitira resultados reproducibles

In [57]:
np.random.seed(12345)
np.random.rand(4,5)

array([[0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503],
       [0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987],
       [0.74771481, 0.96130674, 0.0083883 , 0.10644438, 0.29870371],
       [0.65641118, 0.80981255, 0.87217591, 0.9646476 , 0.72368535]])

Copiar un vector y todos sus atributos

In [ ]:
c = np.array(a,copy=true)

    pandas vectore unidmensionales relacionados con un indice
        data frames permite crear tablas (contenido , indice filas, indice columnas)

In [66]:
 import pandas as pd

dates = pd.date_range('20130101',periods=6)
print(dates)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


A         B         C         D
2013-01-01  0.050009  0.670216  0.852965 -0.955869
2013-01-02 -0.023493 -2.304234 -0.652469 -1.218302
2013-01-03 -1.332610  1.074623  0.723642  0.690002
2013-01-04  1.001543 -0.503087 -0.622274 -0.921169
2013-01-05 -0.726213  0.222896  0.051316 -1.157719
2013-01-06  0.816707  0.433610  1.010737  1.824875